[package]
name = "rusty-linux"
version = "0.1.0"
edition = "2024"


[dependencies]
bitflags = "2.9.0"
bitmaps = { version = "*", default-features = false}
static_assertions = "*"
spin = "*"
heapless = "*"
log = "*"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
